//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class Float64MultiArrayMsg : Message
    {
        public const string k_RosMessageName = "std_msgs/Float64MultiArray";
        public override string RosMessageName => k_RosMessageName;

        public MultiArrayLayoutMsg layout;
        public double[] data;

        public Float64MultiArrayMsg()
        {
            this.layout = new MultiArrayLayoutMsg();
            this.data = new double[0];
        }

        public Float64MultiArrayMsg(MultiArrayLayoutMsg layout, double[] data)
        {
            this.layout = layout;
            this.data = data;
        }

        public static Float64MultiArrayMsg Deserialize(MessageDeserializer deserializer) => new Float64MultiArrayMsg(deserializer);

        private Float64MultiArrayMsg(MessageDeserializer deserializer)
        {
            this.layout = MultiArrayLayoutMsg.Deserialize(deserializer);
            
            int length;
            deserializer.Read(out length);
            this.data = new double[length];
            for (int i = 0; i < length; i++)
            {
                deserializer.Read(out this.data[i]);
            }
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            this.layout.SerializeTo(serializer);
            
            serializer.Write(this.data.Length);
            foreach (double val in this.data)
            {
                serializer.Write(val);
            }
        }

        public override string ToString()
        {
            return "Float64MultiArrayMsg: " +
            "\nlayout: " + layout.ToString() +
            "\ndata: " + string.Join(", ", data);
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }

    // MultiArrayDimension message definition
    [Serializable]
    public class MultiArrayDimensionMsg : Message
    {
        public const string k_RosMessageName = "std_msgs/MultiArrayDimension";
        public override string RosMessageName => k_RosMessageName;

        public string label;
        public uint size;
        public uint stride;

        public MultiArrayDimensionMsg()
        {
            this.label = "";
            this.size = 0;
            this.stride = 0;
        }

        public MultiArrayDimensionMsg(string label, uint size, uint stride)
        {
            this.label = label;
            this.size = size;
            this.stride = stride;
        }

        public static MultiArrayDimensionMsg Deserialize(MessageDeserializer deserializer) => new MultiArrayDimensionMsg(deserializer);

        private MultiArrayDimensionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label);
            deserializer.Read(out this.size);
            deserializer.Read(out this.stride);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.label);
            serializer.Write(this.size);
            serializer.Write(this.stride);
        }

        public override string ToString()
        {
            return "MultiArrayDimensionMsg: " +
            "\nlabel: " + label +
            "\nsize: " + size +
            "\nstride: " + stride;
        }
    }

    // MultiArrayLayout message definition
    [Serializable]
    public class MultiArrayLayoutMsg : Message
    {
        public const string k_RosMessageName = "std_msgs/MultiArrayLayout";
        public override string RosMessageName => k_RosMessageName;

        public MultiArrayDimensionMsg[] dim;
        public uint data_offset;

        public MultiArrayLayoutMsg()
        {
            this.dim = new MultiArrayDimensionMsg[0];
            this.data_offset = 0;
        }

        public MultiArrayLayoutMsg(MultiArrayDimensionMsg[] dim, uint data_offset)
        {
            this.dim = dim;
            this.data_offset = data_offset;
        }

        public static MultiArrayLayoutMsg Deserialize(MessageDeserializer deserializer) => new MultiArrayLayoutMsg(deserializer);

        private MultiArrayLayoutMsg(MessageDeserializer deserializer)
        {
            int length;
            deserializer.Read(out length);
            this.dim = new MultiArrayDimensionMsg[length];
            for (int i = 0; i < length; i++)
            {
                this.dim[i] = MultiArrayDimensionMsg.Deserialize(deserializer);
            }
            deserializer.Read(out this.data_offset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.dim.Length);
            foreach (var val in this.dim)
            {
                val.SerializeTo(serializer);
            }
            serializer.Write(this.data_offset);
        }

        public override string ToString()
        {
            return "MultiArrayLayoutMsg: " +
            "\ndim: [" + string.Join(", ", dim.Select(d => d.ToString())) + "]" +
            "\ndata_offset: " + data_offset;
        }
    }
}
